version: '3.9'
services:

  db:
    image: postgres:alpine3.16
    ports:
      - "5432"
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8080"
    expose:
      - "8080"
    depends_on:
      - db

networks:
  internal:

volumes:
  pgdata:
