# Generated by Django 4.1.3 on 2022-12-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'admin')], editable=False),
        ),
    ]
