# Generated by Django 4.1.3 on 2023-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auth_is_disabled_auth_tmp_token_alter_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
