# Generated by Django 4.1.3 on 2022-12-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auth_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
