# Generated by Django 4.1.3 on 2022-12-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='address',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
