name: Docker

on:
  push:
    branches:
      - "canon"
      - "dev"
    workflow_dispatch:

  pull_request:
    branches:
      - "canon"
      - "dev"
    workflow_dispatch:


jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 14.18

      - run: npm install

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.LOGIN_DOCKERHUB_TEST }}
          password: ${{ secrets.PASSWORD_DOCKERHUB_TEST }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: arkulturtest/bespin

      - name: Build and push canon Docker image
        if: github.ref == 'refs/heads/canon' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: arkulturtest/bespin:canon
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
      - name: Build and push dev docker image
        if: github.ref == 'refs/heads/dev' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: arkulturtest/bespin:dev
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
